# Generated by Django 2.2.7 on 2019-11-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ModifiedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_method', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OriginImage')),
            ],
        ),
    ]
